// admin-front/src/views/Login.tsx
import React, {useState} from 'react'
import styled from "styled-components";
import {Form, Input,Button} from 'antd'
import {useMyForm} from "../hook/useMyForm";
import {loginForm} from "../api/reqInterface";
import {account as rAccount, password as rPassword} from "../untils/FormValidation";
import {LoginRes} from "../api/resInterface";
import {loginApi} from "../api";
const Style = styled('div')`
 .login{
        margin:0;
        background-color: #29f1c3;
        display:flex;
        justify-content:center;
        align-items:center;
        flex-direction:column;
        min-height:100vh;
    }
    .row{
        width: 400px;
        //margin:.6rem 0;
        //position: relative;
        // display:flex;
        // justify-content:center;
        // align-items:center;
        // flex-direction:column;
        // min-height:100vh;
    }
    //.row input{
    //    font-size:1rem;
    //    border: 1px green solid;
    //    border-radius:4px;
    //    box-sizing:border-box;
    //    padding:.8rem 1rem;
    //    box-shadow:0px 1px 2px rgba(0,0,0,.25);
    //    width: 100%;
    //    outline:none;
    //    // placeholder:' ';
    //}
    //.row label{
    //    position:absolute;
    //    left:0px;
    //    padding-left:1rem;
    //    padding-top:.8rem;
    //    transition:all .3s ease-in-out;
    //}
    //.row input:focus + label{
    //    transform:translatex(calc(-100% - 1rem));
    //}
    //.row input:not(:focus):not(:placeholder-shown) + label{
    //    color:rgba(0,0,0,0)
    //}
`
export default function Login() {

   const {form,state,setState,handleSubmit} = useMyForm<loginForm,LoginRes>({
       account:'',
       password:''
   },loginApi,(res)=>{
       console.log(res)
   })

    return (
        <Style>
            <Form className="login" form={form}>
                <h2>管理员登入</h2>
                <div className="row">
                    <Form.Item name={'account'} rules={rAccount} label={'账号'}>
                        <Input type="text" id='username'
                               onChange={e=>setState('account',e)}
                               value={state.account}/>
                        {/*<label htmlFor="username">用户名</label>*/}
                    </Form.Item>

                </div>

                <div className="row">
                    <Form.Item name={'password'} className="row" rules={rPassword} label={'密码'}>
                        <Input type="password" id='pwd'
                               onChange={e=>setState('password',e)}
                               value={state.password}
                        />
                        {/*<label htmlFor="pwd">密码</label>*/}
                    </Form.Item>

                </div>

                <Button onClick={handleSubmit}>登录</Button>
            </Form>
        </Style>
    )
}

// front/src/views/login.vue
<template>
    <div class="main">
        <div class="login_window">
            <div class="content">
                <h1>欢迎你 (≧▽≦)/</h1>
                <a-form layout="block" @submit="handleSubmit" @submit.native.prevent>
                    <a-form-item v-bind="validateInfos.account">
                        <a-input v-model:value="model.account" placeholder="输入用户名"/>
                    </a-form-item>
                    <a-form-item v-bind="validateInfos.password">
                        <a-input
                                v-model:value="model.password"
                                type="password"
                                placeholder="输入密码"
                        />
                    </a-form-item>
                    <a-form-item>
                        <a-button type="primary" html-type="submit"> 登录</a-button>
                    </a-form-item>
                </a-form>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
    import {defineComponent} from "vue";
    import {useFormSet} from "../hooks";
    import {loginApi} from "../api";
    import {loginForm} from "../formInterfaces";
    import {LoginRes} from "../responseInterfaces";
    import {useRouter} from "vue-router";
    import {setToken} from "../untils/cookies";

    export default defineComponent({
        name: "login",
        setup() {
            const $router = useRouter();
            const {
                resetFields,
                validate,
                validateInfos,
                handleSubmit,
                model,
            } = useFormSet<loginForm, LoginRes>(
                {
                    password: "",
                    account: "",
                },
                loginApi, (res) => {
                    setToken(res.token);
                    console.log($router);
                    $router.replace("/");
                }
            );
            return {
                model,
                handleSubmit,
                validateInfos,
            };
        },
    });
</script>

<style lang="less" scoped>
    @keyframes swing {
        0% {
            transform: rotateZ(-1deg);
        }

        100% {
            transform: rotateZ(1deg);
        }
    }

    .main {
        width: 100vw;
        height: 100vh;
        display: flex;
        align-items: center;
        flex-direction: column;
        justify-content: center;
        background-image: url("../assets/backgrounds/deco-wood-02.png"),
        url(../assets/backgrounds/deco-wood-03.png),
        url(../assets/backgrounds/bg-mainvisual-01.gif);
        background-repeat: no-repeat, no-repeat, repeat;
        background-size: 152px auto, 148px auto, 200px auto;
        background-position: right top, left top, left top;
    }

    .login_window {
        transform-origin: center top;
        animation: swing 2s infinite ease-in-out alternate;
        width: 300px;
        height: 450px;
        box-sizing: content-box;
        background-image: url(../assets/components/concept_y_top.gif),
        url(../assets/components/concept_y_bottom.gif),
        url(../assets/components/concept_y_bg.png);
        background-repeat: no-repeat, no-repeat, repeat;
        background-size: 300px auto, 300px auto, 300px auto;
        background-position: top, bottom, center;
        /*background-clip: padding-box;*/
    }

    .content {
        > h1 {
            text-align: center;
            color: #4d4d4d;
        }

        width: inherit;
        height: inherit;
        padding: calc(300 / 366 * 55 * 1px) 30px calc(300 / 366 * 45 * 1px) 30px;
    }
</style>
